version: '3'

services:
  impakt-frontend:
    build: 
      context: ./impakt-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./impakt-frontend/src:/app/src
      - ./impakt-frontend/public:/app/public

networks:
  impakt-network:
    driver: bridge
    
    

